
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class user_signup_frame extends javax.swing.JFrame {

    File f;

    /**
     * Creates new form user_signup_frame
     */
    public user_signup_frame() {
        initComponents();
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(d);
        getContentPane().setBackground(Color.WHITE);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        jp1.setText("");
        jp2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jp1 = new javax.swing.JPasswordField();
        jp2 = new javax.swing.JPasswordField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        lb7 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("USERNAME");
        getContentPane().add(lb1);
        lb1.setBounds(480, 210, 70, 20);

        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("PASSWORD");
        getContentPane().add(lb2);
        lb2.setBounds(480, 250, 80, 14);

        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setText("CONFIRM PASSWORD");
        getContentPane().add(lb3);
        lb3.setBounds(480, 290, 140, 14);

        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setText("EMAIL");
        getContentPane().add(lb4);
        lb4.setBounds(480, 330, 80, 14);

        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setText("PHONE NUMBER");
        getContentPane().add(lb5);
        lb5.setBounds(480, 370, 120, 14);

        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setText("PHOTO");
        getContentPane().add(lb6);
        lb6.setBounds(480, 410, 110, 14);
        getContentPane().add(tf1);
        tf1.setBounds(620, 210, 210, 20);
        getContentPane().add(jp1);
        jp1.setBounds(620, 250, 210, 20);
        getContentPane().add(jp2);
        jp2.setBounds(620, 290, 210, 20);
        getContentPane().add(tf2);
        tf2.setBounds(620, 330, 210, 20);

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(620, 370, 210, 20);
        getContentPane().add(lb7);
        lb7.setBounds(630, 410, 80, 70);

        bt1.setText("BROWSE");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(490, 470, 90, 23);

        bt2.setText("SIGNUP");
        bt2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(610, 520, 90, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER HERE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 20, 230, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 90, 590, 520);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aa.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        String u = tf1.getText();

        String p = jp1.getText();
        String cp = jp2.getText();
        String e = tf2.getText();
        String ph = tf3.getText();

        if (u.isEmpty() || p.isEmpty() || cp.isEmpty() || e.isEmpty() || ph.isEmpty() || f == null) {
            JOptionPane.showMessageDialog(this, "All fields are reqiured...");
        } else if (e.indexOf("@") == -1 || e.indexOf(".") == -1) {
            JOptionPane.showMessageDialog(this, "please fill a valid email");
        } else if (ph.length() != 10) {
            JOptionPane.showMessageDialog(this, "Please fill a valid phone number ");
        } else if (!(p.equals(cp))) {
            JOptionPane.showMessageDialog(this, "password and confirm password must match");
        } else {
            try {
                HttpResponse<String> res = Unirest.post("http://localhost:9000/signup")
                        .queryString("username", u)
                        .queryString("password", p)
                        .queryString("confirm_password", cp)
                        .queryString("email", e)
                        .queryString("phone_number", ph)
                        .field("photo", f)
                        .asString();
                if (res.getStatus() == 200) {
                    String ans = res.getBody();
                    System.out.println("-----------------" + ans);
                    if (ans.equals("success")) {
                        JOptionPane.showMessageDialog(this, "Signup successful");
                        dispose();

                        user_login1 obj = new user_login1();
                    } else {
                        JOptionPane.showMessageDialog(this, "Please Signup from a different Username");
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int ans = chooser.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
        }
        ImageIcon icon = new ImageIcon(f.getPath());
        Image img = icon.getImage().getScaledInstance(lb7.getWidth(), lb7.getHeight(), Image.SCALE_SMOOTH);
        lb7.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_bt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_signup_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_signup_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_signup_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_signup_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_signup_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JPasswordField jp2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
