
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;


 
public class UserMoviePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserMovieFrame
     */
    public UserMoviePanel() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmoviename = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdescription = new javax.swing.JTextArea();
        jamt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(null);

        jmoviename.setText("jLabel1");
        add(jmoviename);
        jmoviename.setBounds(100, 10, 390, 30);

        jphoto.setText("jLabel2");
        add(jphoto);
        jphoto.setBounds(100, 60, 250, 150);

        jdescription.setColumns(20);
        jdescription.setRows(5);
        jScrollPane1.setViewportView(jdescription);

        add(jScrollPane1);
        jScrollPane1.setBounds(150, 230, 240, 96);

        jamt.setText("jLabel3");
        add(jamt);
        jamt.setBounds(250, 340, 100, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 10)); // NOI18N
        jLabel1.setText("MOVIE");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 14);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 10)); // NOI18N
        jLabel2.setText("DESCRIPTION");
        add(jLabel2);
        jLabel2.setBounds(60, 260, 70, 14);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 10)); // NOI18N
        jLabel3.setText("AMOUNT");
        add(jLabel3);
        jLabel3.setBounds(190, 350, 120, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jamt;
    public javax.swing.JTextArea jdescription;
    public javax.swing.JLabel jmoviename;
    public javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
