
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class user_home extends javax.swing.JFrame {

    /**
     * Creates new form user_home
     */
    String user = "";
    Dimension d;

    public user_home(String username) {
        initComponents();
        this.user = username;
        GlobalClass.username = username;
        d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(d.getSize());
        jPanel1.setBounds(0, 0, d.width / 2, 200);
        jPanel2.setBounds(d.width / 2, 0, d.width / 2, d.height);
        jScrollPane1.setBounds(0, 200, d.width / 2, d.height - 300);
        getContentPane().setBackground(Color.WHITE);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        username = user;
        lb1.setText("WELCOME " + user.toUpperCase());
        getUserDetails();
        String images[] = {"src/bingeflixPhotos/action.jpg", "src/bingeflixPhotos/horror.jpg", "src/bingeflixPhotos/jocker.jpg", "src/bingeflixPhotos/fantasy.jpg", "src/bingeflixPhotos/fantasy1.jpg", "src/bingeflixPhotos/kgf1.jpg", "src/bingeflixPhotos/comedy2.jpg", "src/bingeflixPhotos/dil.jpg", "src/bingeflixPhotos/kung.png", "src/bingeflixPhotos/rrr.jpg", "src/bingeflixPhotos/marvel.jpg"};
        final PanelSlider42<JPanel> slider = new PanelSlider42<JPanel>(jPanel2);
        final JPanel jPanel = slider.getBasePanel();
        for (int i = 0; i < images.length; i++) {
            try {
                JLabel lb = new JLabel();

                BufferedImage image = ImageIO.read(new File(images[i]));
                Image img = image.getScaledInstance(jPanel2.getWidth(), jPanel2.getHeight(), Image.SCALE_SMOOTH);
                lb.setIcon(new ImageIcon(img));
                slider.addComponent(lb);
            } catch (Exception ex) {
                ex.printStackTrace();
// Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        slider.test();

        loadCategories();
        setVisible(true);

    }

    public void getUserDetails() {
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:9000/getUserDetail")
                    .queryString("user", user)
                    .asString();
            if (res.getStatus() == 200) {
                String ans = res.getBody();
                if (ans.equals("fails")) {
                    System.out.println("fails");
                } else {
                    String photo = ans;

                    URL url = new URL("http://localhost:9000/getresource/" + photo);
                    BufferedImage img = ImageIO.read(url);
                    Image newimg = img.getScaledInstance(lb2.getWidth(), lb2.getHeight(), Image.SCALE_SMOOTH);
                    lb2.setIcon(new ImageIcon(newimg));

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setLayout(null);

        lb1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("jLabel1");
        jPanel1.add(lb1);
        lb1.setBounds(90, 30, 230, 30);

        lb2.setText("jLabel2");
        jPanel1.add(lb2);
        lb2.setBounds(160, 80, 90, 100);

        bt1.setBackground(new java.awt.Color(255, 204, 204));
        bt1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        bt1.setText("CHANGE PASSWORD");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1);
        bt1.setBounds(420, 90, 180, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 0, 980, 140);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(650, 120, 750, 320);

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setLayout(null);
        jScrollPane1.setViewportView(mainPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 440, 1550, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        user_change_password obj;
        obj = new user_change_password(user);
    }//GEN-LAST:event_bt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void loadCategories() {
        String ans = " ";
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:9000/getAllCategories")
                    .asString();

            if (res.getStatus() == 200) {
                String ans2 = res.getBody();
                System.out.println("-----------------" + ans2);
                StringTokenizer st = new StringTokenizer(ans2, "#$#");
                int count = st.countTokens();

                //decalaration of panels
                CategoryPanelDesign obj[] = new CategoryPanelDesign[count];
                int i = 0;
                int x = 20, y = 20;

                mainPanel.setPreferredSize(new Dimension((d.width / 2) - 50, 380 * count));
                while (st.hasMoreTokens()) {
                    obj[i] = new CategoryPanelDesign();

                    String catDetails = st.nextToken();
                    System.out.println("categoryDetails   " + catDetails);
                    StringTokenizer st2 = new StringTokenizer(catDetails, "**");
                    String catName = st2.nextToken();
                    String desc = st2.nextToken();
                    String photo = st2.nextToken();

                    //create panel
                    obj[i].jCatName.setText(catName);
                    obj[i].jDesc.setText(desc);
                    obj[i].jPhoto.setText(photo);

                    try {
                        URL url = new URL("http://localhost:9000/getresource/" + photo);
                        BufferedImage img = ImageIO.read(url);
                        Image newimg = img.getScaledInstance(obj[i].jPhoto.getWidth(), obj[i].jPhoto.getHeight(), Image.SCALE_SMOOTH);
                        obj[i].jPhoto.setIcon(new ImageIcon(newimg));

                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }

                    obj[i].addMouseListener(new MouseAdapter() {

                        public void mouseClicked(MouseEvent e) {
                            UserMovieFrame obj = new UserMovieFrame(catName);
                        }

                    });

                    obj[i].setBounds(x, y, (d.width / 2) - 50, 350);
                    mainPanel.add(obj[i]);
                    y += 380;
                    i++;
                }

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
