/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author HP
 */
public class video_panel extends javax.swing.JPanel {

    /**
     * Creates new form video_panel
     */
    public video_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jvideo = new javax.swing.JLabel();
        jduration = new javax.swing.JLabel();
        jtitle = new javax.swing.JLabel();
        thumbnail = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(null);

        jvideo.setText("jLabel1");
        add(jvideo);
        jvideo.setBounds(50, 240, 110, 30);

        jduration.setText("jLabel2");
        add(jduration);
        jduration.setBounds(270, 240, 130, 30);

        jtitle.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        add(jtitle);
        jtitle.setBounds(70, 20, 350, 30);

        thumbnail.setText("jLabel4");
        add(thumbnail);
        thumbnail.setBounds(110, 80, 270, 100);

        bt1.setText("PLAY");
        add(bt1);
        bt1.setBounds(10, 310, 150, 40);

        bt2.setText("DOWNLOAD");
        add(bt2);
        bt2.setBounds(230, 310, 150, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt1;
    public javax.swing.JButton bt2;
    public javax.swing.JLabel jduration;
    public javax.swing.JLabel jtitle;
    public javax.swing.JLabel jvideo;
    public javax.swing.JLabel thumbnail;
    // End of variables declaration//GEN-END:variables
}
